# Generated by Django 5.0.1 on 2024-02-18 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tit', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('content', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('content', models.CharField(max_length=200)),
                ('publicacao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.publicacao')),
            ],
        ),
    ]
